//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCaddins.src.SheetCopier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SheetCopierMainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SheetCopierMainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCaddins.src.SheetCopier.SheetCopierMainForm", typeof(SheetCopierMainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles button1_Anchor {
            get {
                object obj = ResourceManager.GetObject("button1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool button1_Enabled {
            get {
                object obj = ResourceManager.GetObject("button1.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle button1_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("button1.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=347,Y=4}.
        /// </summary>
        internal static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=92, Height=23}.
        /// </summary>
        internal static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles button2_Anchor {
            get {
                object obj = ResourceManager.GetObject("button2.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle button2_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("button2.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=233,Y=4}.
        /// </summary>
        internal static System.Drawing.Point button2_Location {
            get {
                object obj = ResourceManager.GetObject("button2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=108, Height=23}.
        /// </summary>
        internal static System.Drawing.Size button2_Size {
            get {
                object obj = ResourceManager.GetObject("button2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 13.
        /// </summary>
        internal static int button2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles button3_Anchor {
            get {
                object obj = ResourceManager.GetObject("button3.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool button3_Enabled {
            get {
                object obj = ResourceManager.GetObject("button3.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle button3_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("button3.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=560,Y=7}.
        /// </summary>
        internal static System.Drawing.Point button3_Location {
            get {
                object obj = ResourceManager.GetObject("button3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=108, Height=23}.
        /// </summary>
        internal static System.Drawing.Size button3_Size {
            get {
                object obj = ResourceManager.GetObject("button3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 14.
        /// </summary>
        internal static int button3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles buttonAdd_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonAdd.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle buttonAdd_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonAdd.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=563,Y=4}.
        /// </summary>
        internal static System.Drawing.Point buttonAdd_Location {
            get {
                object obj = ResourceManager.GetObject("buttonAdd.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=112, Height=23}.
        /// </summary>
        internal static System.Drawing.Size buttonAdd_Size {
            get {
                object obj = ResourceManager.GetObject("buttonAdd.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int buttonAdd_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonAdd.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles buttonGo_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonGo.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle buttonGo_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonGo.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=855,Y=479}.
        /// </summary>
        internal static System.Drawing.Point buttonGo_Location {
            get {
                object obj = ResourceManager.GetObject("buttonGo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size buttonGo_Size {
            get {
                object obj = ResourceManager.GetObject("buttonGo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int buttonGo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonGo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles buttonRemove_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonRemove.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool buttonRemove_Enabled {
            get {
                object obj = ResourceManager.GetObject("buttonRemove.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle buttonRemove_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonRemove.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=445,Y=4}.
        /// </summary>
        internal static System.Drawing.Point buttonRemove_Location {
            get {
                object obj = ResourceManager.GetObject("buttonRemove.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=112, Height=23}.
        /// </summary>
        internal static System.Drawing.Size buttonRemove_Size {
            get {
                object obj = ResourceManager.GetObject("buttonRemove.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int buttonRemove_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonRemove.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles buttonRemoveView_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveView.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool buttonRemoveView_Enabled {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveView.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle buttonRemoveView_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveView.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=442,Y=7}.
        /// </summary>
        internal static System.Drawing.Point buttonRemoveView_Location {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveView.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=108, Height=23}.
        /// </summary>
        internal static System.Drawing.Size buttonRemoveView_Size {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveView.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        internal static int buttonRemoveView_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveView.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 123.
        /// </summary>
        internal static int columnHeader2_Width {
            get {
                object obj = ResourceManager.GetObject("columnHeader2.Width", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles dataGridView1_Anchor {
            get {
                object obj = ResourceManager.GetObject("dataGridView1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=3}.
        /// </summary>
        internal static System.Drawing.Point dataGridView1_Location {
            get {
                object obj = ResourceManager.GetObject("dataGridView1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=672, Height=174}.
        /// </summary>
        internal static System.Drawing.Size dataGridView1_Size {
            get {
                object obj = ResourceManager.GetObject("dataGridView1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int dataGridView1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dataGridView1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles dataGridView2_Anchor {
            get {
                object obj = ResourceManager.GetObject("dataGridView2.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=36}.
        /// </summary>
        internal static System.Drawing.Point dataGridView2_Location {
            get {
                object obj = ResourceManager.GetObject("dataGridView2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=672, Height=211}.
        /// </summary>
        internal static System.Drawing.Size dataGridView2_Size {
            get {
                object obj = ResourceManager.GetObject("dataGridView2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int dataGridView2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dataGridView2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=9}.
        /// </summary>
        internal static System.Drawing.Point label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=184, Height=23}.
        /// </summary>
        internal static System.Drawing.Size label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent[Source] View of Selection.
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=9}.
        /// </summary>
        internal static System.Drawing.Point label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=121, Height=25}.
        /// </summary>
        internal static System.Drawing.Size label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheets.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=12}.
        /// </summary>
        internal static System.Drawing.Point label3_Location {
            get {
                object obj = ResourceManager.GetObject("label3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=284, Height=18}.
        /// </summary>
        internal static System.Drawing.Size label3_Size {
            get {
                object obj = ResourceManager.GetObject("label3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        internal static int label3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views on New Sheet.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles listView1_Anchor {
            get {
                object obj = ResourceManager.GetObject("listView1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ListViewGroup similar to Basic Information.
        /// </summary>
        internal static System.Windows.Forms.ListViewGroup listView1_Groups {
            get {
                object obj = ResourceManager.GetObject("listView1.Groups", resourceCulture);
                return ((System.Windows.Forms.ListViewGroup)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ListViewGroup similar to View Ports.
        /// </summary>
        internal static System.Windows.Forms.ListViewGroup listView1_Groups1 {
            get {
                object obj = ResourceManager.GetObject("listView1.Groups1", resourceCulture);
                return ((System.Windows.Forms.ListViewGroup)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ListViewGroup similar to Schedules.
        /// </summary>
        internal static System.Windows.Forms.ListViewGroup listView1_Groups2 {
            get {
                object obj = ResourceManager.GetObject("listView1.Groups2", resourceCulture);
                return ((System.Windows.Forms.ListViewGroup)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=33}.
        /// </summary>
        internal static System.Drawing.Point listView1_Location {
            get {
                object obj = ResourceManager.GetObject("listView1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool listView1_RightToLeftLayout {
            get {
                object obj = ResourceManager.GetObject("listView1.RightToLeftLayout", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=230, Height=422}.
        /// </summary>
        internal static System.Drawing.Size listView1_Size {
            get {
                object obj = ResourceManager.GetObject("listView1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int listView1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("listView1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles splitContainer1_Anchor {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=12}.
        /// </summary>
        internal static System.Drawing.Point splitContainer1_Location {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=918, Height=461}.
        /// </summary>
        internal static System.Drawing.Size splitContainer1_Size {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 236.
        /// </summary>
        internal static int splitContainer1_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int splitContainer1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("splitContainer1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles splitContainer2_Anchor {
            get {
                object obj = ResourceManager.GetObject("splitContainer2.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=30}.
        /// </summary>
        internal static System.Drawing.Point splitContainer2_Location {
            get {
                object obj = ResourceManager.GetObject("splitContainer2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Orientation similar to Horizontal.
        /// </summary>
        internal static System.Windows.Forms.Orientation splitContainer2_Orientation {
            get {
                object obj = ResourceManager.GetObject("splitContainer2.Orientation", resourceCulture);
                return ((System.Windows.Forms.Orientation)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=672, Height=428}.
        /// </summary>
        internal static System.Drawing.Size splitContainer2_Size {
            get {
                object obj = ResourceManager.GetObject("splitContainer2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 180.
        /// </summary>
        internal static int splitContainer2_SplitterDistance {
            get {
                object obj = ResourceManager.GetObject("splitContainer2.SplitterDistance", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int splitContainer2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("splitContainer2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
