//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCaddins.SpellChecker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class SpellCheckerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SpellCheckerSettings defaultInstance = ((SpellCheckerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SpellCheckerSettings())));
        
        public static SpellCheckerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Autodesk.Revit.DB.Material</string>
  <string>Autodesk.Revit.DB.ProperySetElement</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ElementIgnoreList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ElementIgnoreList"]));
            }
            set {
                this["ElementIgnoreList"] = value;
            }
        }
    }
}
