//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCaddins.ModelSetupWizard {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class ModelSetupWizardSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ModelSetupWizardSettings defaultInstance = ((ModelSetupWizardSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ModelSetupWizardSettings())));
        
        public static ModelSetupWizardSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nominated Architect")]
        public string NomArchitectParamName {
            get {
                return ((string)(this["NomArchitectParamName"]));
            }
            set {
                this["NomArchitectParamName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nominated Architect Number")]
        public string NomArchitectNoumberParamName {
            get {
                return ((string)(this["NomArchitectNoumberParamName"]));
            }
            set {
                this["NomArchitectNoumberParamName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Central Filename")]
        public string FileNameParameterName {
            get {
                return ((string)(this["FileNameParameterName"]));
            }
            set {
                this["FileNameParameterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Revit\\Data\\scaddins_modelsetup_config.xml")]
        public string SystemConfigFilePath {
            get {
                return ((string)(this["SystemConfigFilePath"]));
            }
            set {
                this["SystemConfigFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadSystemConfigOnStartup {
            get {
                return ((bool)(this["LoadSystemConfigOnStartup"]));
            }
            set {
                this["LoadSystemConfigOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>A-Architecture;1</string>
  <string>A-Entourage;0</string>
  <string>A-Façade;True;&lt;/string&gt;</string>
  <string>A-FFE;False;&lt;/string&gt;</string>
  <string>A-Interior Layouts;False;&lt;/string&gt;</string>
  <string>A-Scope Box;0</string>
  <string>A-Shared Levels and Grids;0</string>
  <string>A-Site and Landscape;0</string>
  <string>A-Structure;0</string>
  <string>S.SC-Link RVT-Project Control;0</string>
  <string>S.SC-Link RVT-Cad Container;0</string>
  <string>S.SC-Link RVT-Base Model 1;0</string>
  <string>S.SC-Link RVT-Base Model 2;0</string>
  <string>S.SC-Link RVT-Interior;0</string>
  <string>Z-Link DWG;0</string>
  <string>Z-Link RVT-Electrical0</string>
  <string>Z-Link RVT-Hydraulics;0</string>
  <string>Z-Link RVT-Mechanical;0</string>
  <string>Z-Link RVT-Structure;0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultWorksets {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultWorksets"]));
            }
            set {
                this["DefaultWorksets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Project Number; YYYYMMDD;^[0-9]{8}$</string>
  <string>Project Status;Preliminary</string>
  <string>Project Address;Enter Address Here</string>
  <string>Nominated Architect Number;;^[0-9]{4,5}$</string>
  <string>Organization Name;Studio.SC Pty. Ltd.</string>
  <string>Author;Studio.SC Pty. Ltd.</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultProjectInformation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultProjectInformation"]));
            }
            set {
                this["DefaultProjectInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>Joe Bloggs; 1111</string>\r\n  <string>Mary Lee; 2222</string>\r\n</ArrayOfStr" +
            "ing>")]
        public global::System.Collections.Specialized.StringCollection DefaultArchitectInformation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultArchitectInformation"]));
            }
            set {
                this["DefaultArchitectInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Autumn;595959;59F3FF;63B8F7;7B83E5;A99A73;E6DBA5;B0DCCD;8BA559;999999;99F8FF;9FD3FA;AEB3EF;CAC1A9;EFE9C8;CFEAE0;B8C799</string>
  <string>Spring;595959;59F3FF;63B8F7;7B83E5;EDC059;E6DBA5;B0DCCE;A5D19B;999999;99F8FF;9FD3FA;AEB3EF;F4D899;EFE9C8;CFEAE1;C8E3C1</string>
  <string>Summer;595959;AA59EE;59F3FF;63B8F7;7B83E5;E6DBA5;C3C962;B0DCCE;999999;CB99F5;99F8FF;9FD3FA;AEB3EF;EFE9C8;DADE9F;CFEAE1</string>
  <string>Winter;595959;E6DBA5;B0DCCE;A5D19B;8BA559;94C1E2;7D94CE;8A92B3;999999;EFE9C8;CFEAE1;C8E3C1;B8C799;BDD9ED;AFBDE1;B7BCD1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColourSchemes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColourSchemes"]));
            }
            set {
                this["ColourSchemes"] = value;
            }
        }
    }
}
