//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCaddins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCaddins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current Sheet.
        /// </summary>
        public static string AddCurrentSheet {
            get {
                return ResourceManager.GetString("AddCurrentSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Revision.
        /// </summary>
        public static string AddRevision {
            get {
                return ResourceManager.GetString("AddRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always ask for confirmation before overwriting?.
        /// </summary>
        public static string AlwyasConfirmFileOverwrite {
            get {
                return ResourceManager.GetString("AlwyasConfirmFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Analysis.
        /// </summary>
        public static string AngleOfSun {
            get {
                return ResourceManager.GetString("AngleOfSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Single/Multiple &quot;Sun-Eye&quot; Views; Shadow Plans or Solar Analysis Views..
        /// </summary>
        public static string AngleOfSunLongDescription {
            get {
                return ResourceManager.GetString("AngleOfSunLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar analysis tools..
        /// </summary>
        public static string AngleOfSunToolTip {
            get {
                return ResourceManager.GetString("AngleOfSunToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Print Settings.
        /// </summary>
        public static string ApplyPrintSettings {
            get {
                return ResourceManager.GetString("ApplyPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Level.
        /// </summary>
        public static string AssociatedLevel {
            get {
                return ResourceManager.GetString("AssociatedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed 09/10/2024 13:30:43.36 
        ///.
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Detailing.
        /// </summary>
        public static string CopyDetailing {
            get {
                return ResourceManager.GetString("CopyDetailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Sheets.
        /// </summary>
        public static string CopySheets {
            get {
                return ResourceManager.GetString("CopySheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy a view sheet and all its content, or copy independent views..
        /// </summary>
        public static string CopySheetsToolTip {
            get {
                return ResourceManager.GetString("CopySheetsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create user view.
        /// </summary>
        public static string CouldNotCreateUserView {
            get {
                return ResourceManager.GetString("CouldNotCreateUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Perspective.
        /// </summary>
        public static string CreatePerspective {
            get {
                return ResourceManager.GetString("CreatePerspective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a perspective view from the current view (3d or plan)..
        /// </summary>
        public static string CreatePerspectiveToolTip {
            get {
                return ResourceManager.GetString("CreatePerspectiveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User View.
        /// </summary>
        public static string CreateUserView {
            get {
                return ResourceManager.GetString("CreateUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Views.
        /// </summary>
        public static string CreateUserViews {
            get {
                return ResourceManager.GetString("CreateUserViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destructive Purge.
        /// </summary>
        public static string DestructivePurge {
            get {
                return ResourceManager.GetString("DestructivePurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DestructivePurgeDeleteSelected {
            get {
                return ResourceManager.GetString("DestructivePurgeDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to show additional information.
        /// </summary>
        public static string DestructivePurgeShowAdditionalInfo {
            get {
                return ResourceManager.GetString("DestructivePurgeShowAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Element.
        /// </summary>
        public static string DestructivePurgeShowElement {
            get {
                return ResourceManager.GetString("DestructivePurgeShowElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up your model, in a more destructive way than a purge..
        /// </summary>
        public static string DestructivePurgeToolTip {
            get {
                return ResourceManager.GetString("DestructivePurgeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string DotDotDot {
            get {
                return ResourceManager.GetString("DotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not overwrite file, maybe check permissions?.
        /// </summary>
        public static string ErrorCantOverwriteFile {
            get {
                return ResourceManager.GetString("ErrorCantOverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to assign print setting: .
        /// </summary>
        public static string ErrorFailedToAssignPrintSetting {
            get {
                return ResourceManager.GetString("ErrorFailedToAssignPrintSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to print.
        /// </summary>
        public static string ErrorFailedToPrint {
            get {
                return ResourceManager.GetString("ErrorFailedToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Revit Print Settings FAILED.
        /// </summary>
        public static string ErrorRetrievingRevitPrintSettingsFAILED {
            get {
                return ResourceManager.GetString("ErrorRetrievingRevitPrintSettingsFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Name.
        /// </summary>
        public static string ExistingName {
            get {
                return ResourceManager.GetString("ExistingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Number.
        /// </summary>
        public static string ExistingNumber {
            get {
                return ResourceManager.GetString("ExistingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        public static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Directory.
        /// </summary>
        public static string ExportDirectory {
            get {
                return ResourceManager.GetString("ExportDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing export log.
        /// </summary>
        public static string ExportLogInitializationError {
            get {
                return ResourceManager.GetString("ExportLogInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print A2 (scale to fit).
        /// </summary>
        public static string ExportManagerPrintA2Fit {
            get {
                return ResourceManager.GetString("ExportManagerPrintA2Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print A3 (scale to fit).
        /// </summary>
        public static string ExportManagerPrintA3Fit {
            get {
                return ResourceManager.GetString("ExportManagerPrintA3Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Full Size.
        /// </summary>
        public static string ExportManagerPrintFullSize {
            get {
                return ResourceManager.GetString("ExportManagerPrintFullSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Name.
        /// </summary>
        public static string ExportName {
            get {
                return ResourceManager.GetString("ExportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Started.
        /// </summary>
        public static string ExportStarted {
            get {
                return ResourceManager.GetString("ExportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dwg.
        /// </summary>
        public static string FileExtensionDWG {
            get {
                return ResourceManager.GetString("FileExtensionDWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        public static string FileExtensionPDF {
            get {
                return ResourceManager.GetString("FileExtensionPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ps.
        /// </summary>
        public static string FileExtensionPS {
            get {
                return ResourceManager.GetString("FileExtensionPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xml.
        /// </summary>
        public static string FileExtensionXML {
            get {
                return ResourceManager.GetString("FileExtensionXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: Rev *.
        /// </summary>
        public static string FilterRevisionColumnPrefix {
            get {
                return ResourceManager.GetString("FilterRevisionColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: Rev Date*.
        /// </summary>
        public static string FilterRevisionDateColumnPrefix {
            get {
                return ResourceManager.GetString("FilterRevisionDateColumnPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: Starts with *.
        /// </summary>
        public static string FilterStartsWithPrefix {
            get {
                return ResourceManager.GetString("FilterStartsWithPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expressions to filter the sheetlist. Searches both sheet name and number..
        /// </summary>
        public static string FindToolTipText {
            get {
                return ResourceManager.GetString("FindToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Print.
        /// </summary>
        public static string FinishedPrint {
            get {
                return ResourceManager.GetString("FinishedPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Manager.
        /// </summary>
        public static string GridManager {
            get {
                return ResourceManager.GetString("GridManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Location of Grid Bubbles and Levels Heads.
        /// </summary>
        public static string GridManagerToolTip {
            get {
                return ResourceManager.GetString("GridManagerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatch Editor.
        /// </summary>
        public static string HatchEditor {
            get {
                return ResourceManager.GetString("HatchEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom fill patterns..
        /// </summary>
        public static string HatchEditorToolTip {
            get {
                return ResourceManager.GetString("HatchEditorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Tool.
        /// </summary>
        public static string IncrementTool {
            get {
                return ResourceManager.GetString("IncrementTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment Tool Settings.
        /// </summary>
        public static string IncrementToolSettings {
            get {
                return ResourceManager.GetString("IncrementToolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment room numbers and family marks..
        /// </summary>
        public static string IncrementToolToolTip {
            get {
                return ResourceManager.GetString("IncrementToolToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed Version.
        /// </summary>
        public static string InstalledVersion {
            get {
                return ResourceManager.GetString("InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Sight.
        /// </summary>
        public static string LineofSight {
            get {
                return ResourceManager.GetString("LineofSight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create line of sight details for stadium seating..
        /// </summary>
        public static string LineofSightToolTip {
            get {
                return ResourceManager.GetString("LineofSightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports attempted with.
        /// </summary>
        public static string LogDialogExportsAttempted {
            get {
                return ResourceManager.GetString("LogDialogExportsAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Lua {
            get {
                object obj = ResourceManager.GetObject("Lua", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (apparently) completed successfully.
        /// </summary>
        public static string MessageApparentlyCompletedSuccessfully {
            get {
                return ResourceManager.GetString("MessageApparentlyCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying print setting: .
        /// </summary>
        public static string MessageApplyingPrintSetting {
            get {
                return ResourceManager.GetString("MessageApplyingPrintSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning export options: .
        /// </summary>
        public static string MessageAssigningExportOptions {
            get {
                return ResourceManager.GetString("MessageAssigningExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to hide Title Block (temporarily).
        /// </summary>
        public static string MessageAttemptingToHideTitleBlock {
            get {
                return ResourceManager.GetString("MessageAttemptingToHideTitleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to Load Revit Print Settings: .
        /// </summary>
        public static string MessageAttemptingToLoadRevitPrintSettings {
            get {
                return ResourceManager.GetString("MessageAttemptingToLoadRevitPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set printer: .
        /// </summary>
        public static string MessageCannotSetPrinter {
            get {
                return ResourceManager.GetString("MessageCannotSetPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not apply print settings.
        /// </summary>
        public static string MessageCouldNotApplyPrintSettings {
            get {
                return ResourceManager.GetString("MessageCouldNotApplyPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time for last export: .
        /// </summary>
        public static string MessageElapsedTimeForLastExport {
            get {
                return ResourceManager.GetString("MessageElapsedTimeForLastExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to directory: .
        /// </summary>
        public static string MessageExportingToDirectory {
            get {
                return ResourceManager.GetString("MessageExportingToDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to file name: .
        /// </summary>
        public static string MessageExportingToFileName {
            get {
                return ResourceManager.GetString("MessageExportingToFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No print setting assigned..
        /// </summary>
        public static string MessageNoPrintSettingAssigned {
            get {
                return ResourceManager.GetString("MessageNoPrintSettingAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Title Block.
        /// </summary>
        public static string MessageShowingTitleBlock {
            get {
                return ResourceManager.GetString("MessageShowingTitleBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Starting DWG Export ###.
        /// </summary>
        public static string MessageStartingDWGExport {
            get {
                return ResourceManager.GetString("MessageStartingDWGExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Starting Ghostscript PDF Export ###.
        /// </summary>
        public static string MessageStartingGhostscriptPDFExport {
            get {
                return ResourceManager.GetString("MessageStartingGhostscriptPDFExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Starting Native PDF Export ###.
        /// </summary>
        public static string MessageStartingNativePDFExport {
            get {
                return ResourceManager.GetString("MessageStartingNativePDFExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Starting Adobe PDF Export ###.
        /// </summary>
        public static string MessageStartingPDFExport {
            get {
                return ResourceManager.GetString("MessageStartingPDFExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting print....
        /// </summary>
        public static string MessageSubmittingPrint {
            get {
                return ResourceManager.GetString("MessageSubmittingPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to overwrite existing file: .
        /// </summary>
        public static string MessageUnableToOverwriteExistingFile {
            get {
                return ResourceManager.GetString("MessageUnableToOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using printer: .
        /// </summary>
        public static string MessageUsingPrinter {
            get {
                return ResourceManager.GetString("MessageUsingPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Number.
        /// </summary>
        public static string NewNumber {
            get {
                return ResourceManager.GetString("NewNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Category Name.
        /// </summary>
        public static string NewSheetCategoryName {
            get {
                return ResourceManager.GetString("NewSheetCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheets.
        /// </summary>
        public static string NewSheets {
            get {
                return ResourceManager.GetString("NewSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Point.
        /// </summary>
        public static string NorthPoint {
            get {
                return ResourceManager.GetString("NorthPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North Point Visibility.
        /// </summary>
        public static string NorthPointVisibility {
            get {
                return ResourceManager.GetString("NorthPointVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sheet.
        /// </summary>
        public static string OpenSheet {
            get {
                return ResourceManager.GetString("OpenSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for Multiple View Creation.
        /// </summary>
        public static string OptionsForMultipleViewCreation {
            get {
                return ResourceManager.GetString("OptionsForMultipleViewCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title.
        /// </summary>
        public static string OriginalTitle {
            get {
                return ResourceManager.GetString("OriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent[Source] View of Selection.
        /// </summary>
        public static string ParentSourceViewOfSelection {
            get {
                return ResourceManager.GetString("ParentSourceViewOfSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern.
        /// </summary>
        public static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Coordinate.
        /// </summary>
        public static string PlaceCoordinate {
            get {
                return ResourceManager.GetString("PlaceCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place a family at a specified shared coordinate..
        /// </summary>
        public static string PlaceCoordinateToolTip {
            get {
                return ResourceManager.GetString("PlaceCoordinateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postscript printer name.
        /// </summary>
        public static string PostscriptPrinterName {
            get {
                return ResourceManager.GetString("PostscriptPrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Setting.
        /// </summary>
        public static string PrintSetting {
            get {
                return ResourceManager.GetString("PrintSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Title.
        /// </summary>
        public static string ProposedTitle {
            get {
                return ResourceManager.GetString("ProposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Options.
        /// </summary>
        public static string RegexOptions {
            get {
                return ResourceManager.GetString("RegexOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Underlays from Views.
        /// </summary>
        public static string RemoveUnderlaysfromViews {
            get {
                return ResourceManager.GetString("RemoveUnderlaysfromViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove View.
        /// </summary>
        public static string RemoveView {
            get {
                return ResourceManager.GetString("RemoveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename selected parameters. Rename modes include ToUpper; ToLower; Regex and Regex with Increment..
        /// </summary>
        public static string RenameLongDescription {
            get {
                return ResourceManager.GetString("RenameLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Selected Sheets.
        /// </summary>
        public static string RenameSelectedSheets {
            get {
                return ResourceManager.GetString("RenameSelectedSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Sheets.
        /// </summary>
        public static string RenameSheets {
            get {
                return ResourceManager.GetString("RenameSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename sheets (using regex).
        /// </summary>
        public static string RenameSheetsUsingRegex {
            get {
                return ResourceManager.GetString("RenameSheetsUsingRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Parameters.
        /// </summary>
        public static string RenameToolTip {
            get {
                return ResourceManager.GetString("RenameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Views.
        /// </summary>
        public static string RenameViews {
            get {
                return ResourceManager.GetString("RenameViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Date.
        /// </summary>
        public static string RevisionDate {
            get {
                return ResourceManager.GetString("RevisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Description.
        /// </summary>
        public static string RevisionDescription {
            get {
                return ResourceManager.GetString("RevisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Tools.
        /// </summary>
        public static string RoomTools {
            get {
                return ResourceManager.GetString("RoomTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk rename selected items in the list above..
        /// </summary>
        public static string RoomToolsBulkRename {
            get {
                return ResourceManager.GetString("RoomToolsBulkRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Masses from Rooms.
        /// </summary>
        public static string RoomToolsCreateMasseRadio {
            get {
                return ResourceManager.GetString("RoomToolsCreateMasseRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Masses.
        /// </summary>
        public static string RoomToolsCreateMasses {
            get {
                return ResourceManager.GetString("RoomToolsCreateMasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Plans and Sheets.
        /// </summary>
        public static string RoomToolsCreatePlansAndSheets {
            get {
                return ResourceManager.GetString("RoomToolsCreatePlansAndSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Plans and Sheets from Rooms.
        /// </summary>
        public static string RoomToolsCreatePlansRadio {
            get {
                return ResourceManager.GetString("RoomToolsCreatePlansRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter the room list(above) by selected parameter values..
        /// </summary>
        public static string RoomToolsFilterRoomList {
            get {
                return ResourceManager.GetString("RoomToolsFilterRoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Plan Name.
        /// </summary>
        public static string RoomToolsNewPlanName {
            get {
                return ResourceManager.GetString("RoomToolsNewPlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewSheetName.
        /// </summary>
        public static string RoomToolsNewSheetName {
            get {
                return ResourceManager.GetString("RoomToolsNewSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sheet Number.
        /// </summary>
        public static string RoomToolsNewSheetNumber {
            get {
                return ResourceManager.GetString("RoomToolsNewSheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Name.
        /// </summary>
        public static string RoomToolsRoomName {
            get {
                return ResourceManager.GetString("RoomToolsRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string RoomToolsRoomNumber {
            get {
                return ResourceManager.GetString("RoomToolsRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Masses to Rooms.
        /// </summary>
        public static string RoomToolsSync {
            get {
                return ResourceManager.GetString("RoomToolsSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates sheets and/or solids(masses) from a selection of rooms..
        /// </summary>
        public static string RoomToolsToolTip {
            get {
                return ResourceManager.GetString("RoomToolsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCexport.
        /// </summary>
        public static string SCexport {
            get {
                return ResourceManager.GetString("SCexport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCexport will export file[s] using the internal Revit revision for each sheet, and a predefined naming scheme..
        /// </summary>
        public static string SCexportLongDescription {
            get {
                return ResourceManager.GetString("SCexportLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF/DWG file[s] with pre defined naming standards.
        /// </summary>
        public static string SCexportToolTip {
            get {
                return ResourceManager.GetString("SCexportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Clouds.
        /// </summary>
        public static string ScheduleClouds {
            get {
                return ResourceManager.GetString("ScheduleClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule revision clouds and/or re-assign revisions to them..
        /// </summary>
        public static string ScheduleCloudsToolTip {
            get {
                return ResourceManager.GetString("ScheduleCloudsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Revision Cloud To Schedule,Delete or Re-assign.
        /// </summary>
        public static string SelectRevisionCloudToScheduleDeleteOrAssign {
            get {
                return ResourceManager.GetString("SelectRevisionCloudToScheduleDeleteOrAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Revision To Schedule.
        /// </summary>
        public static string SelectRevisionToSchedule {
            get {
                return ResourceManager.GetString("SelectRevisionToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Printer.
        /// </summary>
        public static string SetPrinter {
            get {
                return ResourceManager.GetString("SetPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Category.
        /// </summary>
        public static string SheetCategory {
            get {
                return ResourceManager.GetString("SheetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Category Name.
        /// </summary>
        public static string SheetCategoryName {
            get {
                return ResourceManager.GetString("SheetCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string SheetName {
            get {
                return ResourceManager.GetString("SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Number.
        /// </summary>
        public static string SheetNumber {
            get {
                return ResourceManager.GetString("SheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Shadow Plans.
        /// </summary>
        public static string SolarViewsCreateMultipleShadowPlans {
            get {
                return ResourceManager.GetString("SolarViewsCreateMultipleShadowPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Angle of Sun Views (3d).
        /// </summary>
        public static string SolarViewsCreateMultipleSunViews {
            get {
                return ResourceManager.GetString("SolarViewsCreateMultipleSunViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate Current View.
        /// </summary>
        public static string SolarViewsRotateCurrentView {
            get {
                return ResourceManager.GetString("SolarViewsRotateCurrentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string SpacerHyphen {
            get {
                return ResourceManager.GetString("SpacerHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Print.
        /// </summary>
        public static string StartingPrint {
            get {
                return ResourceManager.GetString("StartingPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to Load Revit Print Settings:.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Run.
        /// </summary>
        public static string TestRun {
            get {
                return ResourceManager.GetString("TestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Complete Change Log.
        /// </summary>
        public static string UpdateViewChangeLog {
            get {
                return ResourceManager.GetString("UpdateViewChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCaddins is up to date. Nice one..
        /// </summary>
        public static string UpgradeUpToDateMessage {
            get {
                return ResourceManager.GetString("UpgradeUpToDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available!. Click Download (go on, you can do it).
        /// </summary>
        public static string UpgrateNewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("UpgrateNewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking installed version.
        /// </summary>
        public static string UpgrateVersionCheckErrorMessage {
            get {
                return ResourceManager.GetString("UpgrateVersionCheckErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User View.
        /// </summary>
        public static string UserView {
            get {
                return ResourceManager.GetString("UserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a user view..
        /// </summary>
        public static string UserViewToolTip {
            get {
                return ResourceManager.GetString("UserViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Sheets.
        /// </summary>
        public static string VerifySheets {
            get {
                return ResourceManager.GetString("VerifySheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Template.
        /// </summary>
        public static string ViewTemplate {
            get {
                return ResourceManager.GetString("ViewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Type.
        /// </summary>
        public static string ViewType {
            get {
                return ResourceManager.GetString("ViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF export disabled, check settings!!!.
        /// </summary>
        public static string WarningPDFExportDisabled {
            get {
                return ResourceManager.GetString("WarningPDFExportDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Setup is read only!.
        /// </summary>
        public static string WarningPrintSetupReadOnly {
            get {
                return ResourceManager.GetString("WarningPrintSetupReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: could not set window style.
        /// </summary>
        public static string WindowManager_Window_SourceInitialized_WARNING__could_not_set_window_style {
            get {
                return ResourceManager.GetString("WindowManager_Window_SourceInitialized_WARNING__could_not_set_window_style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
