//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCaddins.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCaddins.Common.AboutBox", typeof(AboutBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Left.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles button1_Anchor {
            get {
                object obj = ResourceManager.GetObject("button1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=329}.
        /// </summary>
        internal static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=129, Height=23}.
        /// </summary>
        internal static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 28.
        /// </summary>
        internal static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelCopyright_Dock {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=195,Y=48}.
        /// </summary>
        internal static System.Drawing.Point labelCopyright_Location {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelCopyright_Margin {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelCopyright_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=377, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelCopyright_Size {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        internal static int labelCopyright_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string labelCopyright_Text {
            get {
                return ResourceManager.GetString("labelCopyright.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelCopyright_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelProductName_Dock {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=195,Y=0}.
        /// </summary>
        internal static System.Drawing.Point labelProductName_Location {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelProductName_Margin {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelProductName_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelProductName.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=377, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelProductName_Size {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        internal static int labelProductName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelProductName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string labelProductName_Text {
            get {
                return ResourceManager.GetString("labelProductName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelProductName_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelProductName.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle labelVersion_Dock {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=195,Y=24}.
        /// </summary>
        internal static System.Drawing.Point labelVersion_Location {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        internal static System.Windows.Forms.Padding labelVersion_Margin {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelVersion_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelVersion.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=377, Height=17}.
        /// </summary>
        internal static System.Drawing.Size labelVersion_Size {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int labelVersion_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelVersion.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string labelVersion_Text {
            get {
                return ResourceManager.GetString("labelVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        internal static System.Drawing.ContentAlignment labelVersion_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelVersion.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool linkLabel1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("linkLabel1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=192,Y=272}.
        /// </summary>
        internal static System.Drawing.Point linkLabel1_Location {
            get {
                object obj = ResourceManager.GetObject("linkLabel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=28, Height=13}.
        /// </summary>
        internal static System.Drawing.Size linkLabel1_Size {
            get {
                object obj = ResourceManager.GetObject("linkLabel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 26.
        /// </summary>
        internal static int linkLabel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("linkLabel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        internal static string linkLabel1_Text {
            get {
                return ResourceManager.GetString("linkLabel1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool linkLabel2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("linkLabel2.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=192,Y=296}.
        /// </summary>
        internal static System.Drawing.Point linkLabel2_Location {
            get {
                object obj = ResourceManager.GetObject("linkLabel2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=13}.
        /// </summary>
        internal static System.Drawing.Size linkLabel2_Size {
            get {
                object obj = ResourceManager.GetObject("linkLabel2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 27.
        /// </summary>
        internal static int linkLabel2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("linkLabel2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string linkLabel2_Text {
            get {
                return ResourceManager.GetString("linkLabel2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle logoPictureBox_Dock {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoPictureBox_Image {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoPictureBox_InitialImage {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.InitialImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=3}.
        /// </summary>
        internal static System.Drawing.Point logoPictureBox_Location {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=183, Height=314}.
        /// </summary>
        internal static System.Drawing.Size logoPictureBox_Size {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to CenterImage.
        /// </summary>
        internal static System.Windows.Forms.PictureBoxSizeMode logoPictureBox_SizeMode {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        internal static int logoPictureBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles okayButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("okayButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=497,Y=329}.
        /// </summary>
        internal static System.Drawing.Point okayButton_Location {
            get {
                object obj = ResourceManager.GetObject("okayButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        internal static System.Drawing.Size okayButton_Size {
            get {
                object obj = ResourceManager.GetObject("okayButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 24.
        /// </summary>
        internal static int okayButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("okayButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int tableLayoutPanel_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle tableLayoutPanel_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        internal static System.Windows.Forms.TableLayoutSettings tableLayoutPanel_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=9}.
        /// </summary>
        internal static System.Drawing.Point tableLayoutPanel_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int tableLayoutPanel_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=575, Height=355}.
        /// </summary>
        internal static System.Drawing.Size tableLayoutPanel_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int tableLayoutPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        internal static System.Windows.Forms.DockStyle textBoxDescription_Dock {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=195,Y=75}.
        /// </summary>
        internal static System.Drawing.Point textBoxDescription_Location {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=3,Right=3,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding textBoxDescription_Margin {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool textBoxDescription_Multiline {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Multiline", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ScrollBars similar to Both.
        /// </summary>
        internal static System.Windows.Forms.ScrollBars textBoxDescription_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.ScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=377, Height=194}.
        /// </summary>
        internal static System.Drawing.Size textBoxDescription_Size {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 23.
        /// </summary>
        internal static int textBoxDescription_TabIndex {
            get {
                object obj = ResourceManager.GetObject("textBoxDescription.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string textBoxDescription_Text {
            get {
                return ResourceManager.GetString("textBoxDescription.Text", resourceCulture);
            }
        }
    }
}
